InputEmail          = "//input[@id='login-email-textfield']"
InputPassword       = "//input[@id='login-password-passfield']"
ButtonLogin         = "//button[@id='login-signin-button']"
MessageErrorLogin   = "//div[contains(text(),'The account sign-in was incorrect or your account ')]"
MyAccountPage      = "//h2[normalize-space()='Account information']"
LinkToLogin         = "//a[@id='header-menu-btnsign']"