InputFirstname                  = "//input[@id='register-firstname-textfield']"
InputLastname                   = "//input[@id='register-lastname-textfield']"
InputEmail                      = "//input[@id='register-email-textfield']"
InputPassword                   = "//input[@id='register-password-passfield']"
InputPasswordConfirmation       = "//input[@id='register-passwordConfirm-textfield']"
InputPhoneNumber                = "//input[@value='+62']"
RegisterWACheckbox              = "//input[@id='register-waRegitered-checkbox']"
LinkToRegister                  = "//a[@id='header-menu-btnregister']"
ButtonSendOTP                   = "//button[@id='plugin-sendotp-btn']"
ButtonVerifyOTP                 = "//button[@id='plugin-verifyotp-btn']"
ButtonRegister                  = "//button[@id='register-btnRegister']"
LabelEmailRequired              = "//p[normalize-space()='Email is required']"
MyAccountPage                   = "//h2[normalize-space()='Account information']"